name: CI - Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Checkout the repository code using Node.js v20
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: 20  # Enforce Node.js v20 for the action

      # Set up the specified Node.js version for the workflow itself
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Run tests
      - name: Run Tests
        id: test
        run: npm test

      # Check if 'coverage' folder exists
      - name: Check if coverage exists
        id: coverage_check
        run: |
          if [ -d "coverage" ]; then
            echo "coverage-exists=true" >> $GITHUB_OUTPUT
          else
            echo "coverage-exists=false" >> $GITHUB_OUTPUT
          fi

      # Upload coverage results if the folder exists
      - name: Upload Coverage Results
        if: success() && steps.coverage_check.outputs['coverage-exists'] == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: coverage
